site_name: Bangladesh Law
site_url: https://bangladeshlaw.github.io
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
  
  font:
    text: Tiro Bangla
    code: Tiro Bangla

  language: bn
  logo: assets/flag.svg
  favicon: assets/flag.svg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.instant.prefetch
    - navigation.instant.progress
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer


extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: বাংলা
      link: /bn/
      lang: bn
  generator: false
  social:
    - icon: fontawesome/brands/square-github 
      link: https://github.com/abusayed0206
  

plugins:
  - search
  - social:
      cards_layout_options:
        font_family: "Tiro Bangla"
